<?php

/**
 * Hooks and side effects to configure Posts.
 *
 * Default routes generated by WordPress Posts
 * are pruned. Routing of Posts should be based
 * solely on `permalink_structure`.
 */

/**
 * Disable date-based routing.
 */
add_filter( 'date_rewrite_rules', '__return_empty_array', 99 );

/**
 * Filters rewrite rules used for "post" archives.
 *
 * This function disables:
 * - Feeds
 * - Comments
 * - Directory iteration
 *
 * @listens filter:post_rewrite_rules
 *
 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
 *
 * @return string[]
 */
add_filter( 'post_rewrite_rules', function () : array {
    global $wp_rewrite;

    // Disable verbose page rules to ensure post rewrite rules come first
    $wp_rewrite->use_verbose_page_rules = false;

    // Rebuild post routes
    return $wp_rewrite->generate_rewrite_rules(
        $wp_rewrite->permalink_structure,
        EP_PERMALINK,
        true,   // paged
        true,   // feed
        false,  // forcomments
        false,  // walk_dirs
        true    // endpoints
    );
}, 5 );

/**
 * Filters rewrite rules used for root-level archives.
 *
 * This function disables:
 * - Pagination
 * - Feeds
 * - Comments
 * - Directory iteration
 *
 * @listens filter:root_rewrite_rules
 *
 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
 *
 * @return string[]
 */
add_filter( 'root_rewrite_rules', function () : array {
    global $wp_rewrite;

    $root_rules = $wp_rewrite->generate_rewrite_rules(
        $wp_rewrite->root . '/',
        EP_ROOT,
        false,  // paged
        false,  // feed
        false,  // forcomments
        false,  // walk_dirs
        true    // endpoints
    );

    /**
     * Ensure an archive root is generated for the Post post type.
     *
     * Logic based on {@see WP_Rewrite::add_rewrite_rules()}.
     */
    if ( $wp_rewrite->front ) {
        $archive_slug = trim( $wp_rewrite->front, '/' );
        $feeds = '(' . trim( implode( '|', $wp_rewrite->feeds ) ) . ')';
        add_rewrite_rule( "{$archive_slug}/?$", "index.php?post_type=post", 'top' );
        add_rewrite_rule( "{$archive_slug}/feed/{$feeds}/?$", "index.php?post_type=post" . '&feed=$matches[1]', 'top' );
        add_rewrite_rule( "{$archive_slug}/{$feeds}/?$", "index.php?post_type=post" . '&feed=$matches[1]', 'top' );
        add_rewrite_rule( "{$archive_slug}/{$wp_rewrite->pagination_base}/([0-9]{1,})/?$", "index.php?post_type=post" . '&paged=$matches[1]', 'top' );
    }

    return $root_rules;
}, 5 );
